import type { Metadata } from "next";
import "./globals.css";
import { outfit } from "./font";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable}`}
      >
        <main className="bg-primary-foreground ">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
