export const sponsors = [
    {
        "id": 1,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Anonymous",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723477153195 L-1723477153195"
    },
    {
        "id": 2,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Donna and Art Appel",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723481036578 L-1723481036578"
    },
    {
        "id": 3,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Lovick & Mary Anthony",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484015801 L-1723484015801"
    },
    {
        "id": 4,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Sandra Appignani and Mark Baumgarten",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484016081 L-1723484016081"
    },
    {
        "id": 5,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Ronni and Sheldon Aptekar",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484016295 L-1723484016295"
    },
    {
        "id": 6,
        "numberOfPanelsDonated": 10,
        "amount": 25000,
        "messageType": null,
        "recogntionText": "In honor of James and Maryann Armour",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484016472 L-1723484016472"
    },
    {
        "id": 7,
        "numberOfPanelsDonated": 25,
        "amount": 60000,
        "messageType": null,
        "recogntionText": "In honor of Tena Arnesen",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484016682 L-1723484016682"
    },
    {
        "id": 8,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Atlas Insurance",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484016872 L-1723484016872"
    },
    {
        "id": 9,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of B2 Communications",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484017095 L-1723484017095"
    },
    {
        "id": 10,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Crystal, Charlie, and Claire Bailey",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484017330 L-1723484017330"
    },
    {
        "id": 11,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Robert and Ginger Bailey",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484017579 L-1723484017579"
    },
    {
        "id": 12,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of the Robert D. Baker Family",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484017791 L-1723484017791"
    },
    {
        "id": 13,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Pat and Judith Ball",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484017995 L-1723484017995"
    },
    {
        "id": 14,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Robert G. and M. Beverly Bartner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484018212 L-1723484018212"
    },
    {
        "id": 15,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Tom and Marie Belcher",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484018448 L-1723484018448"
    },
    {
        "id": 16,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Jeffrey and Jessica Benesch and family",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484018659 L-1723484018659"
    },
    {
        "id": 17,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Michael and Sara Benesch",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484018879 L-1723484018879"
    },
    {
        "id": 18,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Allison Archbold and Hugh Bettendorf",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484019081 L-1723484019081"
    },
    {
        "id": 19,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Jim and Linda Bodycomb",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484019294 L-1723484019294"
    },
    {
        "id": 20,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Booker High School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484019533 L-1723484019533"
    },
    {
        "id": 21,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Booker Middle School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484019758 L-1723484019758"
    },
    {
        "id": 22,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In Memory of John S. Bozik",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484019955 L-1723484019955"
    },
    {
        "id": 23,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Meredith Brady",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484020175 L-1723484020175"
    },
    {
        "id": 24,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Steven Brady",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484020390 L-1723484020390"
    },
    {
        "id": 25,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Brookside Middle School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484020629 L-1723484020629"
    },
    {
        "id": 26,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Rob Brown and Rosemary Eure",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484020823 L-1723484020823"
    },
    {
        "id": 27,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Isabella Cordaro Brown",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484021006 L-1723484021006"
    },
    {
        "id": 28,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Julia Cordaro Brown",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484021221 L-1723484021221"
    },
    {
        "id": 29,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Julie Burton and Alexis Burton",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484021428 L-1723484021428"
    },
    {
        "id": 30,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Kathy and Michael Bush",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484021665 L-1723484021665"
    },
    {
        "id": 31,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Rhonda Byrd",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484021874 L-1723484021874"
    },
    {
        "id": 32,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Ronald Brian Christie",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484022099 L-1723484022099"
    },
    {
        "id": 33,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of David and Stephanie Citron",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484022291 L-1723484022291"
    },
    {
        "id": 34,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Trevor Claude",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484022498 L-1723484022498"
    },
    {
        "id": 35,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Marie and Roy Cohen",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484022712 L-1723484022712"
    },
    {
        "id": 36,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Honoring the Conservatory \"My Little Bit of Heaven",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484022891 L-1723484022891"
    },
    {
        "id": 37,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Arthur Cope",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484023147 L-1723484023147"
    },
    {
        "id": 38,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Gianluca Roberto Cordaro",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484023359 L-1723484023359"
    },
    {
        "id": 39,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Vivian Carmen Cordaro",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484023555 L-1723484023555"
    },
    {
        "id": 40,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of B.J. Creighton",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484023811 L-1723484023811"
    },
    {
        "id": 41,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Carole Crosby and Larry Wickless",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484024037 L-1723484024037"
    },
    {
        "id": 42,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Wendy and Michael Deming",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484024232 L-1723484024232"
    },
    {
        "id": 43,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Daniel Denton",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484024458 L-1723484024458"
    },
    {
        "id": 44,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of David Denton",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484024699 L-1723484024699"
    },
    {
        "id": 45,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Rina and Gene Eisenberg",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484024940 L-1723484024940"
    },
    {
        "id": 46,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Ulrich Elben",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484025150 L-1723484025150"
    },
    {
        "id": 47,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Elizabeth and Douglas Elder",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484025355 L-1723484025355"
    },
    {
        "id": 48,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Judy Fiala",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484025556 L-1723484025556"
    },
    {
        "id": 49,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Jane Gould and Stephen Fillo",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484025805 L-1723484025805"
    },
    {
        "id": 50,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Aaron Fink and Vicki Porter-Fink",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484026056 L-1723484026056"
    },
    {
        "id": 51,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of John Finkbohner and Lawrence Miller",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484026283 L-1723484026283"
    },
    {
        "id": 52,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Fontana Consulting",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484026510 L-1723484026510"
    },
    {
        "id": 53,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Henry Anthony and Carol Geiger",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484026731 L-1723484026731"
    },
    {
        "id": 54,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Charles & Alma Geiger",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484026975 L-1723484026975"
    },
    {
        "id": 55,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Gocio Elementary School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484027234 L-1723484027234"
    },
    {
        "id": 59,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Paula and Douglas Griffin",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484028179 L-1723484028179"
    },
    {
        "id": 60,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Scott Gurr",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484028375 L-1723484028375"
    },
    {
        "id": 63,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Teri A Hansen",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484029075 L-1723484029075"
    },
    {
        "id": 64,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Teri Hansen from Susan Buck",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484029294 L-1723484029294"
    },
    {
        "id": 67,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Penny Hill",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484029921 L-1723484029921"
    },
    {
        "id": 70,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "Huisking Foundation",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484030583 L-1723484030583"
    },
    {
        "id": 73,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Sophia Joerger",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484031251 L-1723484031251"
    },
    {
        "id": 77,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Deborah Kalb",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484032599 L-1723484032599"
    },
    {
        "id": 79,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "David Kaminski MD",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484033197 L-1723484033197"
    },
    {
        "id": 82,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of the Kennedy Family Foundation",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484033910 L-1723484033910"
    },
    {
        "id": 83,
        "numberOfPanelsDonated": 10,
        "amount": 25000,
        "messageType": null,
        "recogntionText": "In honor of Carolyn Keystone and James Meekison",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484034266 L-1723484034266"
    },
    {
        "id": 85,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Ashley Rose Korszen",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484035062 L-1723484035062"
    },
    {
        "id": 86,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Theodore Alexander Korszen",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484035858 L-1723484035858"
    },
    {
        "id": 87,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Louis and Cosette Kosiba",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484036119 L-1723484036119"
    },
    {
        "id": 89,
        "numberOfPanelsDonated": 10,
        "amount": 25000,
        "messageType": null,
        "recogntionText": "In honor of David Kotok and Christine Schlesinger",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484036840 L-1723484036840"
    },
    {
        "id": 90,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of the Kutya Major Foundation",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484037059 L-1723484037059"
    },
    {
        "id": 92,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of the Lahners family",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484037519 L-1723484037519"
    },
    {
        "id": 93,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Mark Lancaster and Nancy Woodruff",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484037700 L-1723484037700"
    },
    {
        "id": 94,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Laurel Nokomis School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484037916 L-1723484037916"
    },
    {
        "id": 95,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Harry Leopold and Audrey Robbins",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484038384 L-1723484038384"
    },
    {
        "id": 96,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Jeanne Leszcynski and Diane DiCarlo",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484038589 L-1723484038589"
    },
    {
        "id": 98,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Steven and Lisa Lichtman",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484039043 L-1723484039043"
    },
    {
        "id": 101,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Dr. and Mrs. Carlyle A. Luer",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484040091 L-1723484040091"
    },
    {
        "id": 104,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Tracy Maeter",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484040690 L-1723484040690"
    },
    {
        "id": 107,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Orion Marx and Atlas Insurance",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484041291 L-1723484041291"
    },
    {
        "id": 111,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Applauding Selby: Everett Roy McComb",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484042465 L-1723484042465"
    },
    {
        "id": 121,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Mary Ann and John Meyer",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484044671 L-1723484044671"
    },
    {
        "id": 123,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Sandra Miller",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484045126 L-1723484045126"
    },
    {
        "id": 124,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Hudson Monda",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484045351 L-1723484045351"
    },
    {
        "id": 126,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Richard and Pamela Mones",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484045771 L-1723484045771"
    },
    {
        "id": 127,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Lynn A. Morey, Jr., Dad of Pam, Cheryl, Lynn, and Kim",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484045965 L-1723484045965"
    },
    {
        "id": 129,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Jeffrey Bain and Anat Moskowitz",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484046409 L-1723484046409"
    },
    {
        "id": 130,
        "numberOfPanelsDonated": 10,
        "amount": 25000,
        "messageType": null,
        "recogntionText": "In honor of Richard and Betty Watt Nimtz",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484046615 L-1723484046615"
    },
    {
        "id": 131,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of North Port High School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484046836 L-1723484046836"
    },
    {
        "id": 136,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Pine View High School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484048302 L-1723484048302"
    },
    {
        "id": 138,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Michael and Mary Quillen",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484048850 L-1723484048850"
    },
    {
        "id": 139,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Stephen M. Railsback",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484049163 L-1723484049163"
    },
    {
        "id": 141,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Owen Wells Rhodes Jr.",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484049754 L-1723484049754"
    },
    {
        "id": 142,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Mr. Riggs",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484049991 L-1723484049991"
    },
    {
        "id": 143,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of John David Riner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484050211 L-1723484050211"
    },
    {
        "id": 144,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of John David Riner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484050451 L-1723484050451"
    },
    {
        "id": 145,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Magnolia Riner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484050675 L-1723484050675"
    },
    {
        "id": 146,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Paloma Riner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484050882 L-1723484050882"
    },
    {
        "id": 149,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Marta Riordan and James Boyle",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484051621 L-1723484051621"
    },
    {
        "id": 150,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Sandra Ripberger and Mary Lou Warner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484051997 L-1723484051997"
    },
    {
        "id": 152,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of the Rominiecki Family",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484052578 L-1723484052578"
    },
    {
        "id": 154,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Meyer Sachs",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484053074 L-1723484053074"
    },
    {
        "id": 156,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Adele Sales",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484053554 L-1723484053554"
    },
    {
        "id": 157,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Declan Sales",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484053771 L-1723484053771"
    },
    {
        "id": 158,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Ethan Sales",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484054092 L-1723484054092"
    },
    {
        "id": 159,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Rowan Sales",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484054331 L-1723484054331"
    },
    {
        "id": 56,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Jean Weidner Goldstein from Susan Buck",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484027471 L-1723484027471"
    },
    {
        "id": 57,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Margaret Gonta",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484027695 L-1723484027695"
    },
    {
        "id": 58,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Scott and Candy Greer",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484027913 L-1723484027913"
    },
    {
        "id": 61,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of the Robert G. and Ellen S. Gutenstein Family Foundation",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484028591 L-1723484028591"
    },
    {
        "id": 62,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Mary Evelyn Guyton",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484028839 L-1723484028839"
    },
    {
        "id": 65,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Gary Heard",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484029538 L-1723484029538"
    },
    {
        "id": 66,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Heron Creek Middle School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484029739 L-1723484029739"
    },
    {
        "id": 68,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Stephanie and Allen Hochfelder",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484030137 L-1723484030137"
    },
    {
        "id": 69,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Anita Holec",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484030364 L-1723484030364"
    },
    {
        "id": 71,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Gayle Jackson and Stuart Schwartz",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484030804 L-1723484030804"
    },
    {
        "id": 72,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Schuyler Joerger",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484031035 L-1723484031035"
    },
    {
        "id": 74,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Campbell Johnson, grandchild of Marsha and Richard Johnson",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484031794 L-1723484031794"
    },
    {
        "id": 75,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Caroline Johnson, grandchild of Marsha and Richard Johnson",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484032015 L-1723484032015"
    },
    {
        "id": 76,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Nicholas (Cole) Johnson, grandchild of Marsha and Richard Johnson",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484032275 L-1723484032275"
    },
    {
        "id": 78,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Anna Kaminski MD",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484032951 L-1723484032951"
    },
    {
        "id": 80,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Kwi Cha Kang",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484033482 L-1723484033482"
    },
    {
        "id": 81,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Honoring my grandchildren, Taylor, Ella Grace, Brandon, and Anna Kathryn",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484033716 L-1723484033716"
    },
    {
        "id": 84,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Marcy and Michael Klein",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484034835 L-1723484034835"
    },
    {
        "id": 88,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Philip and Nancy Kotler",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484036630 L-1723484036630"
    },
    {
        "id": 91,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Diana Lager",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484037277 L-1723484037277"
    },
    {
        "id": 97,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Christina Lewis",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484038811 L-1723484038811"
    },
    {
        "id": 99,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In Honor of Courtney M. Loyer",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484039254 L-1723484039254"
    },
    {
        "id": 100,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Drs. Carlyle Luer and Calaway Dodson, and in honor of Dr. Kiat Tan",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484039886 L-1723484039886"
    },
    {
        "id": 102,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Thomas and Allison Luzier",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484040296 L-1723484040296"
    },
    {
        "id": 103,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Ann and Robert Madden",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484040491 L-1723484040491"
    },
    {
        "id": 105,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Flora Major",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484040897 L-1723484040897"
    },
    {
        "id": 106,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Sheila R. Markin",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484041099 L-1723484041099"
    },
    {
        "id": 108,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of J. Richard and Cornelia Matson's 45th wedding anniversary",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484041522 L-1723484041522"
    },
    {
        "id": 109,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Celia Max",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484041717 L-1723484041717"
    },
    {
        "id": 110,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of John C. Mayer",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484042258 L-1723484042258"
    },
    {
        "id": 112,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Applauding Selby: Jenni Gunyakrit Phuntong McComb",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484042674 L-1723484042674"
    },
    {
        "id": 113,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Applauding Selby: John Depke McComb",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484042877 L-1723484042877"
    },
    {
        "id": 114,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Applauding Selby: Kyle Patrick McComb",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484043111 L-1723484043111"
    },
    {
        "id": 115,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Applauding Selby: Whitney Lovell McComb",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484043311 L-1723484043311"
    },
    {
        "id": 116,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Applauding Selby: William Lewis McComb, Jr.",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484043535 L-1723484043535"
    },
    {
        "id": 117,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Chris and Julene McDevitt",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484043771 L-1723484043771"
    },
    {
        "id": 118,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Melissa McDowell",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484044015 L-1723484044015"
    },
    {
        "id": 119,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of McIntosh Middle School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484044231 L-1723484044231"
    },
    {
        "id": 120,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Marla Mehlman",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484044454 L-1723484044454"
    },
    {
        "id": 122,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Peter Miller and Martha Harrison",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484044889 L-1723484044889"
    },
    {
        "id": 125,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Violet Monda",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484045556 L-1723484045556"
    },
    {
        "id": 128,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Peg Morey, Mom of Pam, Cheryl, Lynn, and Kim",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484046176 L-1723484046176"
    },
    {
        "id": 132,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Honoring the Selby Team’s Vision for a Greener Future & Leadership in Sustainability - Overland Partners",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484047080 L-1723484047080"
    },
    {
        "id": 133,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Francesca and Fred Ozdoba",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484047407 L-1723484047407"
    },
    {
        "id": 134,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Kyle Parks",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484047827 L-1723484047827"
    },
    {
        "id": 135,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Charlotte and Charles Perret",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484048056 L-1723484048056"
    },
    {
        "id": 137,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Linda Prowten and Bert Mitchell",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484048492 L-1723484048492"
    },
    {
        "id": 140,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Melissa Rhodes",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484049442 L-1723484049442"
    },
    {
        "id": 147,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Rhodes Riner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484051118 L-1723484051118"
    },
    {
        "id": 148,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Wells Riner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484051318 L-1723484051318"
    },
    {
        "id": 151,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Riverview High School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484052215 L-1723484052215"
    },
    {
        "id": 153,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Sam and Terry Roth",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484052795 L-1723484052795"
    },
    {
        "id": 155,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Shai Sachs",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484053323 L-1723484053323"
    },
    {
        "id": 161,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Sarasota Middle School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484054791 L-1723484054791"
    },
    {
        "id": 163,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Robert and Marcia Schaub",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484055370 L-1723484055370"
    },
    {
        "id": 160,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Sarasota High School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484054554 L-1723484054554"
    },
    {
        "id": 162,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Stacy Schaeffler and Mitchell Schwartz",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484055130 L-1723484055130"
    },
    {
        "id": 164,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Rick and Joni Scherrer",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484055570 L-1723484055570"
    },
    {
        "id": 165,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Debora and John Schneider",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484055769 L-1723484055769"
    },
    {
        "id": 166,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "Sea Grape Foundation",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484055996 L-1723484055996"
    },
    {
        "id": 167,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Annette Shames",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484056436 L-1723484056436"
    },
    {
        "id": 168,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Col.(ret.) Elwood H. Shemwell",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484056788 L-1723484056788"
    },
    {
        "id": 169,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Genevieve Kavanaugh Shemwell",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484057012 L-1723484057012"
    },
    {
        "id": 170,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of our children: Paris, Browning and Reed Shemwell. Given by their proud parents Bob and Jennifer Shemwell.",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484057394 L-1723484057394"
    },
    {
        "id": 171,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Lucinda T. Spaney",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484057656 L-1723484057656"
    },
    {
        "id": 172,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of the Stainbrook family",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484057873 L-1723484057873"
    },
    {
        "id": 173,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Dorothy Stockbridge-Pratt",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484058117 L-1723484058117"
    },
    {
        "id": 174,
        "numberOfPanelsDonated": 10,
        "amount": 25000,
        "messageType": null,
        "recogntionText": "In honor of Dr. Laurey T. Stryker and Charles Stryker",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484058334 L-1723484058334"
    },
    {
        "id": 175,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Suncoast Polytechnical High School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484058565 L-1723484058565"
    },
    {
        "id": 176,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Janis and Hobart Swan",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484058776 L-1723484058776"
    },
    {
        "id": 177,
        "numberOfPanelsDonated": 4,
        "amount": 10000,
        "messageType": null,
        "recogntionText": "In honor of Marcia Jean Taub and Peter Swain",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484059017 L-1723484059017"
    },
    {
        "id": 178,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Julia Nix Trampe",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484059241 L-1723484059241"
    },
    {
        "id": 179,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Andy and Karin Tugendhat",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484059514 L-1723484059514"
    },
    {
        "id": 180,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Marlo and Jay Turner",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484059742 L-1723484059742"
    },
    {
        "id": 181,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Venice Middle School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484059986 L-1723484059986"
    },
    {
        "id": 182,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor Venice High School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484060218 L-1723484060218"
    },
    {
        "id": 183,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "Karen Wehner and James Jurick",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484060453 L-1723484060453"
    },
    {
        "id": 184,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of David Welle and Rosemary Reinhardt",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484060661 L-1723484060661"
    },
    {
        "id": 185,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Ernest Werlin",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484060866 L-1723484060866"
    },
    {
        "id": 186,
        "numberOfPanelsDonated": 2,
        "amount": 5000,
        "messageType": null,
        "recogntionText": "In honor of Elton and Gordie White",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484061072 L-1723484061072"
    },
    {
        "id": 187,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Hans Wiehler",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484061432 L-1723484061432"
    },
    {
        "id": 188,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In memory of Stephen V.C. Wilberding",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484061630 L-1723484061630"
    },
    {
        "id": 189,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Michael, Jena, and Hays Wilson",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484061852 L-1723484061852"
    },
    {
        "id": 190,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Margaret Wise",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484062124 L-1723484062124"
    },
    {
        "id": 191,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Margaret Wise from Susan Buck",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484062384 L-1723484062384"
    },
    {
        "id": 192,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Woodland Middle School",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484062598 L-1723484062598"
    },
    {
        "id": 193,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of the Woodyard family",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484062807 L-1723484062807"
    },
    {
        "id": 194,
        "numberOfPanelsDonated": 1,
        "amount": 2500,
        "messageType": null,
        "recogntionText": "In honor of Emily and Marty Zielke",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1723484063003 L-1723484063003"
    },
    {
        "id": 195,
        "numberOfPanelsDonated": 42,
        "amount": 100000,
        "messageType": null,
        "recogntionText": "Elizabeth Moore",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "F-1724795537479 L-1724795537479"
    },
    {
        "id": 197,
        "numberOfPanelsDonated": 144,
        "amount": 350000,
        "messageType": null,
        "recogntionText": "Charles & Margery Barancik Foundation",
        "logo": "1725413695437-Baranick Foundation Logo.png",
        "companyName": "Charles & Margery Barancik Foundation",
        "companyEmail": "barancik@sunraise.io",
        "country": null,
        "__entity": "SponsorEntity",
        "name": "Barancik Foundation L-1725413695590"
    },
    {
        "id": 217,
        "numberOfPanelsDonated": 10,
        "amount": 5,
        "messageType": "",
        "recogntionText": "Patrick Attwater",
        "logo": null,
        "companyName": null,
        "companyEmail": null,
        "country": null,
        "__entity": "SponsorEntity",
        "name": "Patrick Attwater"
    },
    {
        "id": 218,
        "numberOfPanelsDonated": 20,
        "amount": 5,
        "messageType": null,
        "recogntionText": null,
        "logo": "1725897841105-One80 Solar - Horizontal - White Background (Larger).png",
        "companyName": "One80 Solar",
        "companyEmail": "patrickattwater@gmail.com",
        "country": "United States",
        "__entity": "SponsorEntity",
        "name": "Patrick Attwater"
    }
]

export const colors = [
    {
        bgColor: '#bbe1d2',
        color: '#93d1b8'
    },
    {
        bgColor: '#ffeea2',
        color: '#fffbe7'
    },
    {
        bgColor: '#abd0e7',
        color: '#c5e9ff'
    }
];